### PR TITLE
Refactoring #14 #16

### PR DESCRIPTION
**Pull request by badsgahhl**
This PR is a work in progress to simplify and refactor some parts of the project.
This PR includes:
- Added GPL 3 license #16 
- Simplification of the sm_sticker command without the need of any signatures
- Updated skin & sticker ids
- Game Data Patch for PTaH as there is no updated zip file remotely #14

### CODE REVIEW

**Comment by badsgahhl** [comment]
I will test this more in the next week's and write you again to merge the PR.

In regards to the license, I am going to change it to MIT. I have no favorite there.

**Comment by andreas-mausch** [comment]
Is this still WIP or ready to merge?

**Comment by badsgahhl** [comment]
Can be merged 👍🏼

**Comment by andreas-mausch** [comment]
Thanks for the contribution

**Pull request merged**
